### ISSUE TITLE
Fabric implementation Todo-List

### ISSUE THREAD

**Issue by Xalcon** [Xalcon/TorchMaster#192]
- [ ] Event implemtation: `onCheckSpawn`
- [ ] Event implementation: `onDoSpecialSpawn` 
- [ ] Event implementation: `onVillageSiege`
- [x] Event implementation: `onServerLevelTickEnd`
- [ ] Config File
- [ ] Github Workflow integration
