### ISSUE TITLE
[MC 1.13] Update Todo

### ISSUE THREAD

**Issue by Xalcon** [Xalcon/TorchMaster#84]
- [x] Make it compile on 1.13
- [ ] Reimplement GUI
- [ ] Reimplement config
- [ ] Fix Item Models
- [ ] Fix Block Models
- [ ] Fix Furnace Fuel Handling for Terrain Lighter
- [ ] Fix Crash when placing Terrain Lighter
- [ ] Port SimpleNetworkWrapper Code to SimpleChannel

**Comment by Xalcon** [comment]
Since 1.13.2 was pretty much skipped by forge, I'll not update torchmaster to 1.13.2 and instead go for 1.14.2 directly.
